Add support for avc1 and avc3 stream formats and remove H264.RemoteStream
membraneframework/membrane-caps-video-h264 pull request #9
Opened 2023-08-10 13:42 UTC by Noarkhh

- Add `stream_structure` field and type to H264 that describes the format of the stream as either annexb, avc1 (with DCR) or avc3 (with DCR).
- Remove `H264.RemoteStream` stream format and give it's role of describing unparsed or DCR having H264 stream to H264 stream format.

2023-08-21 08:02 UTC, varsill requested changes

2023-08-21 08:02 UTC, varsill commented on lib/membrane_h264_format/h264.ex
> +  Describes h264 stream structure.
```suggestion
  Describes H264 stream structure.
```

2023-08-21 08:02 UTC, varsill commented on lib/membrane_h264_format/h264.ex
> +  Describes h264 stream structure.
I guess this is the correct styling, we can also change the other occurrences of `h264` into `H264` :D

2023-08-21 08:02 UTC, varsill commented on lib/membrane_h264_format/h264.ex
> +  The length of these prefixes is contained in the stream's DCR Avc streams are more suitable for
```suggestion
  The length of these prefixes is contained in the stream's DCR. AVC streams are more suitable for
```

2023-08-21 08:02 UTC, varsill commented on lib/membrane_h264_format/h264.ex
> +  the stream (in-band).
There is something missing there ;)

2023-08-21 12:30 UTC, Noarkhh commented on lib/membrane_h264_format/h264.ex
> +  the stream (in-band).
yes, forgot to push

2023-08-22 12:26 UTC, varsill approved these changes

2023-08-25 09:59 UTC, merged